### ISSUE TITLE
Distribute streamdeck through f-droid

### ISSUE THREAD

**Issue by arthurzenika** [ecrax/streamdeck#20]
streamdeck looks promising. 

It would be nice to have it shipped using f-droid https://f-droid.org/ 

> F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. The client makes it easy to browse, install, and keep track of updates on your device.

https://gitlab.com/fdroid/rfp to request inclusion (with the documented process there)

**Comment by ecrax** [comment]
Hey, sorry for the late response, GitHub somehow messed up my notifications, but I hope you will still read this. 
I support projects like f-droid (I just had a request to upload a VSCode extension to a FOSS marketplace), but I don't think that streamdeck is ready to be released on a marketplace. It still has some nasty bugs no one is willing to fix and it was meant to be a personal test anyway.
Maybe one day I will continue working on this but for now, I will just leave this GitHub repo as is. :)
