### ISSUE TITLE
server.py not running missing "obspython" can't install obspython with npm

### ISSUE THREAD

**Issue by amoldybuffalo** [ecrax/streamdeck#21]
title

**Comment by ecrax** [comment]
The python module "obspython" is packaged with OBS and is being injected into the python installation used by OBS at runtime. Installing the module is therefore pointless, especially with npm as npm is a package manager for node, which is not used in this project.
I think you may be running the server.py with pure python. Just follow the instructions [here](https://ecrax.github.io/streamdeck/#/quickstart?id=usage) and it should work. :)

**Comment by amoldybuffalo** [comment]
I'm legitimately an idiot. I've been doing web dev stuff with node a lot
lately and I forgot it's pip not npm. Oh wait I didn't read any guides. Was
I supposed to inject server.py into obs rather than running python
server.py? I better read the guide before I sound like an idiot again.

**Comment by amoldybuffalo** [comment]
Ok, I got it. This won't actually work for me since it's obs functions
only. Oh well. Sorry for posting after it's closed etc. Have a nice day,
sorry for being an idiot.

**Comment by ecrax** [comment]
All good, don't call yourself an idiot we all make mistakes :).

**Comment by amoldybuffalo** [comment]
Haha, thanks!
